import { test } from 'node:test'
import assert from 'node:assert/strict'
import { dailySeed, generateGrid, encodeChallenge, decodeChallenge } from '../src/index.js'

// These vectors were generated by SchulteLab's production engine — the
// open-source implementation must match them byte for byte.
const VECTORS = [
  {
    date: '2026-09-01',
    seed: 20260901,
    grid3: '2,9,5,3,6,1,4,8,7',
    grid5: '17,14,11,9,16,4,10,21,20,6,13,2,18,24,8,25,22,7,5,15,3,1,12,23,19',
    letters: 'Q,N,K,I,P,D,J,U,T,F,M,B,R,X,H,Y,V,G,E,O,C,A,L,W,S',
  },
  {
    date: '2026-08-31',
    seed: 20260831,
    grid3: '8,5,2,4,6,3,9,1,7',
    grid5: '25,19,17,14,3,6,5,10,24,23,4,13,7,8,18,1,15,21,9,16,12,11,22,2,20',
    letters: 'Y,S,Q,N,C,F,E,J,X,W,D,M,G,H,R,A,O,U,I,P,L,K,V,B,T',
  },
  {
    date: '2026-01-01',
    seed: 20260101,
    grid3: '9,8,2,1,4,7,6,5,3',
    grid5: '13,11,23,18,5,10,6,20,14,17,9,24,1,12,21,4,2,25,8,3,16,22,19,15,7',
    letters: 'M,K,W,R,E,J,F,T,N,Q,I,X,A,L,U,D,B,Y,H,C,P,V,S,O,G',
  },
]

for (const v of VECTORS) {
  test(`dailySeed(${v.date}) = ${v.seed}`, () => {
    assert.equal(dailySeed(new Date(v.date + 'T00:00:00Z')), v.seed)
  })
  test(`grid 3x3 numbers ${v.date}`, () => {
    assert.equal(generateGrid(3, 'numbers', v.seed).map((c) => c.value).join(','), v.grid3)
  })
  test(`grid 5x5 numbers ${v.date}`, () => {
    assert.equal(generateGrid(5, 'numbers', v.seed).map((c) => c.value).join(','), v.grid5)
  })
  test(`grid 5x5 letters ${v.date}`, () => {
    assert.equal(generateGrid(5, 'letters', v.seed).map((c) => c.value).join(','), v.letters)
  })
}

test('challenge encode/decode round-trip', () => {
  const p = { v: 1, seed: 20260901, size: 5, mode: 'classic', content: 'numbers', t: 21400 }
  assert.deepEqual(decodeChallenge(encodeChallenge(p)), p)
})

test('decodeChallenge rejects malformed input', () => {
  assert.equal(decodeChallenge('not-a-token'), null)
  assert.equal(decodeChallenge(''), null)
})
